image: gitpod/workspace-full
ports:
  - port: 1000-8079
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 9000-9999
    onOpen: ignore
tasks:
  - before: pip3 install -r requirements.txt 
    init: pipwin install -r requirements2.txt
    command: python3 Python_VoiceRecognition/Python_VoiceRecognition.py 
